// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAde8VPH_7vwD2sYykDB71sJCsU9Dxrjmo',
    appId: '1:644670662487:web:d25b3386ea57f1eef1c012',
    messagingSenderId: '644670662487',
    projectId: 'tourmaker-b6612',
    authDomain: 'tourmaker-b6612.firebaseapp.com',
    storageBucket: 'tourmaker-b6612.appspot.com',
    measurementId: 'G-VF17S6KQYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltEGgGvAszL7D6AVX5Q2DH3qNb40AC0g',
    appId: '1:644670662487:android:1868a6c537b85ed9f1c012',
    messagingSenderId: '644670662487',
    projectId: 'tourmaker-b6612',
    storageBucket: 'tourmaker-b6612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rSFbKuk5hQAcwom8QjRwFcYgbXLQ8Ps',
    appId: '1:644670662487:ios:8e2e3572c03d5066f1c012',
    messagingSenderId: '644670662487',
    projectId: 'tourmaker-b6612',
    storageBucket: 'tourmaker-b6612.appspot.com',
    iosClientId:
        '644670662487-m0s267pi103hp38kujh8dd8042p57c49.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rSFbKuk5hQAcwom8QjRwFcYgbXLQ8Ps',
    appId: '1:644670662487:ios:8e2e3572c03d5066f1c012',
    messagingSenderId: '644670662487',
    projectId: 'tourmaker-b6612',
    storageBucket: 'tourmaker-b6612.appspot.com',
    iosClientId:
        '644670662487-m0s267pi103hp38kujh8dd8042p57c49.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourMaker',
  );
}
