part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const String HOME = _Paths.HOME;
  static const String SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const String GET_STARTED = _Paths.GET_STARTED;
  static const String LOGIN = _Paths.LOGIN;
  static const String MAIN_SCREEN = _Paths.MAIN_SCREEN;
  static const String OTP_SCREEN = _Paths.OTP_SCREEN;
  static const String TERMS_AND_CONDITIONS = _Paths.TERMS_AND_CONDITIONS;
  static const String LUCKY_DRAW = _Paths.LUCKY_DRAW;
  static const String PROFILE = _Paths.PROFILE;
  static const String PAYMENT_SCREEN = _Paths.PAYMENT_SCREEN;
  static const String PAYMENT_SUMMARY = _Paths.PAYMENT_SUMMARY;
  static const String FAVOURITES_SCREEN = _Paths.FAVOURITES_SCREEN;
  static const String BOOKING_SCREEN = _Paths.BOOKING_SCREEN;
  static const String TRIP_DETAILS = _Paths.TRIP_DETAILS;
  static const String FILTER_SCREEN = _Paths.FILTER_SCREEN;
  static const String DESTINATIONS = _Paths.DESTINATIONS;
  static const String BUDGET = _Paths.BUDGET;
  static const String CATEGORY = _Paths.CATEGORY;
  static const String DURATION = _Paths.DURATION;
  static const String SEARCH_VIEW = _Paths.SEARCH_VIEW;
  static const String TOKEN_SCREEN = _Paths.TOKEN_SCREEN;
  static const String REWARDS = _Paths.REWARDS;
  static const String RAZORPAY = _Paths.RAZORPAY;
  static const String SINGLE_TOUR = _Paths.SINGLE_TOUR;
  static const String PASSENGER_DETAILS = _Paths.PASSENGER_DETAILS;
  static const String SINGLE_CATEGORY = _Paths.SINGLE_CATEGORY;
  static const String SEARCH_DETAILS = _Paths.SEARCH_DETAILS;
  static const String NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const String NOINTERNET = _Paths.NOINTERNET;
  static const String TOURS_VIEW = _Paths.TOURS_VIEW;
  static const String PDF = _Paths.PDF;
  static const String ADD_PASSENGER = _Paths.ADD_PASSENGER;
  static const String PDF_VIEW = _Paths.PDF_VIEW;
  static const String USER_REGISTERSCREEN = _Paths.USER_REGISTERSCREEN;
  static const String TRENDING_TOURS = _Paths.TRENDING_TOURS;
  static const String EXCLUSIVE_TOURS = _Paths.EXCLUSIVE_TOURS;
  static const String TRAVEL_TYPES = _Paths.TRAVEL_TYPES;
  static const String SINGLE_TRAVEL_TYPETOUR = _Paths.SINGLE_TRAVEL_TYPETOUR;
  static const String CHECKOUT_SCREEN = _Paths.CHECKOUT_SCREEN;
  static const String TRAVELLERS_SCREEN = _Paths.TRAVELLERS_SCREEN;
  static const String SINGLE_PASSENGER = _Paths.SINGLE_PASSENGER;
  static const String MAANGAATHOLI = _Paths.MAANGAATHOLI;
}

abstract class _Paths {
  _Paths._();
  static const String HOME = '/home';
  static const String SPLASH_SCREEN = '/splash-screen';
  static const String GET_STARTED = '/get-started';
  static const String LOGIN = '/login';
  static const String MAIN_SCREEN = '/main-screen';
  static const String OTP_SCREEN = '/otp-screen';
  static const String TERMS_AND_CONDITIONS = '/terms-and-conditions';
  static const String LUCKY_DRAW = '/lucky-draw';
  static const String PROFILE = '/profile';
  static const String PAYMENT_SCREEN = '/payment-screen';
  static const String PAYMENT_SUMMARY = '/payment-summary';
  static const String FAVOURITES_SCREEN = '/favourites-screen';
  static const String BOOKING_SCREEN = '/booking-screen';
  static const String TRIP_DETAILS = '/trip-details';
  static const String FILTER_SCREEN = '/filter-screen';
  static const String DESTINATIONS = '/destinations';
  static const String BUDGET = '/budget';
  static const String CATEGORY = '/category';
  static const String DURATION = '/duration';
  static const String SEARCH_VIEW = '/search-view';
  static const String TOKEN_SCREEN = '/token-screen';
  static const String REWARDS = '/rewards';
  static const String RAZORPAY = '/razorpay';
  static const String SINGLE_TOUR = '/single-tour';
  static const String PASSENGER_DETAILS = '/passenger-details';
  static const String SINGLE_CATEGORY = '/single-category';
  static const String SEARCH_DETAILS = '/search-details';
  static const String NOTIFICATIONS = '/notifications';
  static const String NOINTERNET = '/nointernet';
  static const String TOURS_VIEW = '/tours-view';
  static const String PDF = '/pdf';
  static const String ADD_PASSENGER = '/add-passenger';
  static const String PDF_VIEW = '/pdf-view';
  static const String USER_REGISTERSCREEN = '/user-registerscreen';
  static const String TRENDING_TOURS = '/trending-tours';
  static const String EXCLUSIVE_TOURS = '/exclusive-tours';
  static const String TRAVEL_TYPES = '/travel-types';
  static const String SINGLE_TRAVEL_TYPETOUR = '/single-travel-typetour';
  static const String CHECKOUT_SCREEN = '/checkout-screen';
  static const String TRAVELLERS_SCREEN = '/travellers-screen';
  static const String SINGLE_PASSENGER = '/single-passenger';
  static const String MAANGAATHOLI = '/maangaatholi';
}
